### ISSUE TITLE
Map rendering issue

### ISSUE THREAD

**Issue by cesarhernandezgt** [World-Wide-JUGs/GlobalWWJugs#19]
Current map page: https://world-wide-jugs.github.io/GlobalWWJugs/map doesn't render the map properly.

It seems to be related with the service we use for map returning a 403  https://github.com/World-Wide-JUGs/GlobalWWJugs/blob/gh-pages/map.html#L54

![image](https://user-images.githubusercontent.com/1454523/109598785-9b7eb480-7adf-11eb-94fd-f14ac3fa7d5b.png)

This issue doesn't occur when running the site locally.

cc: @icougil

**Comment by icougil** [comment]
The map right now is using Mapbox (see the [FAQ](https://github.com/Leaflet/Leaflet/blob/master/FAQ.md#data-providers)). I created an account and in order not to have quota abuse, it is restricted to use from only a few places. That is why the map was retrieving an error with a 403. Now it is solved adding the valid domain in the accepted domains
